if (size(agentsSeq,1)>=2)
    k=2;
    kk=3;
    wh_plot
    plot(data(1,:),data(2,:),['.' 'b']...
    ,data(1,agentsSeq(k,:)),data(2,agentsSeq(k,:)),['*-' 'g']...
    ,data(1,agentsSeq(kk,:)),data(2,agentsSeq(kk,:)),['*-' 'b']...
    ,data(1,agentsSeq(k,1)),data(2,agentsSeq(k,1)),['p' 'r']...
    ,data(1,agentsSeq(kk,1)),data(2,agentsSeq(kk,1)),['p' 'r'])
    s1 = CalculateEnergy(agentsSeq(k,:),data');
    s2 = CalculateEnergy(agentsSeq(kk,:),data');
    legend('vacant',num2str(k),num2str(kk))
    title(sprintf(['two agents voyage, S_1=' num2str(s1) ...
        ' S_2=' num2str(s2) ...
        ' S=' num2str(s1+s2)]))
end